### ISSUE TITLE
Incompatible with Python 3.11

### ISSUE THREAD

**Issue by dotlambda** [elupus/arcam_fmj#19]
```
$ python3.11 -c 'import arcam.fmj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/qgj2dy01385nbga6vw4xny7d5l7rs3dy-python3.11-arcam-fmj-1.2.0/lib/python3.11/site-packages/arcam/fmj/__init__.py", line 143, in <module>
    class IntOrTypeEnum(enum.IntEnum):
  File "/nix/store/qgj2dy01385nbga6vw4xny7d5l7rs3dy-python3.11-arcam-fmj-1.2.0/lib/python3.11/site-packages/arcam/fmj/__init__.py", line 153, in IntOrTypeEnum
    def _create_pseudo_member_(cls, value):
  File "/nix/store/l87x5cpmxpfxb93nl4madnr4mmmlvhy4-python3-3.11.1/lib/python3.11/enum.py", line 382, in __setitem__
    raise ValueError(
ValueError: _sunder_ names, such as '_create_pseudo_member_', are reserved for future Enum use
```

**Comment by elupus** [comment]
Ugh.. that will be somewhat messy to solve :). I will look at a solution.
