### ISSUE TITLE
Cannot connect to AVR360

### ISSUE THREAD

**Issue by Setaas** [elupus/arcam_fmj#3]
Hi, 
I am facing some issues when it comes to the connection with my AVR 360. I know it might be not supported, but would like to make sure and will not waste my time with it anymore. 

From the logs, I can see following:
Logger: arcam.fmj.utils

Unable to get device description from http://192.168.0.101:8080/dd.xml
Unable to get device description from http://192.160.0.101:8080/dd.xml

But if I am accessing Arcam directly from a browser, response is received.
This XML file does not appear to have any style information associated with it. The document tree is shown below.
```xml
<root xmlns="urn:schemas-upnp-org:device-1-0" xmlns:pnpx="http://schemas.microsoft.com/windows/pnpx/2005/11" xmlns:microsoft="urn:schemas-microsoft-com:WMPNSS-1-0" xmlns:df="http://schemas.microsoft.com/windows/2008/09/devicefoundation">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>
<presentationURL>/web</presentationURL>
<pnpx:X_hardwareId>VEN_2A2D&DEV_0001&SUBSYS_0001&REV_01 VEN_0033&DEV_0005&REV_01</pnpx:X_hardwareId>
<pnpx:X_compatibleId>MS_DigitalMediaDeviceClass_DMR_V001</pnpx:X_compatibleId>
<pnpx:X_deviceCategory>MediaDevices</pnpx:X_deviceCategory>
<df:X_deviceCategory>Multimedia.DMR</df:X_deviceCategory>
<microsoft:magicPacketWakeSupported>0</microsoft:magicPacketWakeSupported>
<microsoft:magicPacketSendSupported>1</microsoft:magicPacketSendSupported>
<dlna:X_DLNADOC xmlns:dlna="urn:schemas-dlna-org:device-1-0">DMR-1.50</dlna:X_DLNADOC>
<friendlyName>Arcam media client 002261a55190</friendlyName>
<manufacturer>A & R Cambridge</manufacturer>
<manufacturerURL>http://www.arcam.co.uk</manufacturerURL>
<modelDescription>ir-ser-FS2026-0200-0115_V2.2.14.37060-8</modelDescription>
<modelName> </modelName>
<modelNumber> </modelNumber>
<modelURL>http://www.arcamradio.co.uk</modelURL>
<serialNumber>0b05031407351f2701005201xxxxxxxx</serialNumber>
<UDN>uuid:3dcc7100-f76c-11dd-87af-xxxxxxxxxxx</UDN>
<iconList>
<icon>
<mimetype>image/png</mimetype>
<width>48</width>
<height>48</height>
<depth>32</depth>
<url>/icon.png</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>48</width>
<height>48</height>
<depth>32</depth>
<url>/icon.jpg</url>
</icon>
<icon>
<mimetype>image/png</mimetype>
<width>120</width>
<height>120</height>
<depth>32</depth>
<url>/icon2.png</url>
</icon>
<icon>
<mimetype>image/jpeg</mimetype>
<width>120</width>
<height>120</height>
<depth>32</depth>
<url>/icon2.jpg</url>
</icon>
</iconList>
<serviceList>
<service>
<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>
<serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>
<SCPDURL>AVTransport/scpd.xml</SCPDURL>
<controlURL>AVTransport/control</controlURL>
<eventSubURL>AVTransport/event</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</serviceType>
<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>
<SCPDURL>ConnectionManager/scpd.xml</SCPDURL>
<controlURL>ConnectionManager/control</controlURL>
<eventSubURL>ConnectionManager/event</eventSubURL>
</service>
<service>
<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</serviceType>
<serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>
<SCPDURL>RenderingControl/scpd.xml</SCPDURL>
<controlURL>RenderingControl/control</controlURL>
<eventSubURL>RenderingControl/event</eventSubURL>
</service>
</serviceList>
</device>
</root>
```

Can you please have a look what might be wrong?
Thanks in advance!
Best regards,
T

**Comment by elupus** [comment]
Can you enable debug logging for the component? https://www.home-assistant.io/integrations/logger/

You need to enable the following to the logs section.
```yaml
arcane.fmj: debug
```

**Comment by Setaas** [comment]
[home-assistant - Copy.log](https://github.com/elupus/arcam_fmj/files/6468190/home-assistant.-.Copy.log)

Log attached. Finally I managed to create an integration, but I used port 80 instead of default 50000.
Even if device/entity is available, it is not reacting on any triggers.

configuration.yaml modified by:
logger:
 arcam.fmj: debug 

Thanks for your help in this topic!
BR, Tomasz

**Comment by elupus** [comment]
Using port 80 is just invalid. Please give me a log on default port.

**Comment by Setaas** [comment]
Logger: arcam.fmj.utils
Source: /usr/local/lib/python3.8/site-packages/arcam/fmj/utils.py:45
First occurred: 8:28:32 PM (1 occurrences)
Last logged: 8:28:32 PM

Unable to get device description from http://192.168.0.1:8080/dd.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arcam/fmj/utils.py", line 60, in get_uniqueid_from_device_description
    async with session.get(url) as req:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.1:8080 ssl:default [Connect call failed ('192.168.0.1', 8080)]

**Comment by Setaas** [comment]
My mistake, here is correct one:

2021-05-12 20:44:11 ERROR (MainThread) [arcam.fmj.utils] Unable to get device description from http://192.168.0.101:8080/dd.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.101', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arcam/fmj/utils.py", line 60, in get_uniqueid_from_device_description
    async with session.get(url) as req:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:8080 ssl:default [Connect call failed ('192.168.0.101', 8080)]

**Comment by Setaas** [comment]
But seems like even if I am leaving default 50000, 8080 is used underneath.

**Comment by elupus** [comment]
It will always use 8080. It's hardcoded for grabbing unique id. 50000 will be used for the normal communication. I suppose i could allow it to try 80 too, if it fail at 8080.

You got me confused in the initial report, there you said it worked to get `http://192.168.0.101:8080/dd.xml` in a webbrowser, but what you actually did was grab `http://192.168.0.101:80/dd.xml`?

**Comment by Setaas** [comment]
You are right, dd.xml cannot be access using 8080, it was from 80.

**Comment by elupus** [comment]
Anyway. This is only for unique id. It should not block adding the device. So you must be getting other errors later.

**Comment by Setaas** [comment]
So, no chance to have connection established?

**Comment by elupus** [comment]
not before i see a log. as i said, the error you gave above was just for unique id. it should not block adding the device.

**Comment by Setaas** [comment]
Shall I add device using 80 and send the logs later on?

**Comment by Setaas** [comment]
Using 50000 it cannot be added and nothing else it being thrown.

**Comment by elupus** [comment]
when you say it cannot be added, it must be giving you an error either in log or in gui

**Comment by Setaas** [comment]
2021-05-12 22:05:10 ERROR (MainThread) [arcam.fmj.utils] Unable to get device description from http://192.168.0.101:8080/dd.xml
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.0.101', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/arcam/fmj/utils.py", line 60, in get_uniqueid_from_device_description
    async with session.get(url) as req:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.101:8080 ssl:default [Connect call failed ('192.168.0.101', 8080)]
2021-05-12 22:05:10 DEBUG (MainThread) [arcam.fmj.client] Connecting to 192.168.0.101:50000

**Comment by Setaas** [comment]
The same which I pasted an hour ago - nothing else is thrown.

**Comment by elupus** [comment]
```
2021-05-12 22:05:10 DEBUG (MainThread) [arcam.fmj.client] Connecting to 192.168.0.101:50000
```
Okey, that looks like your receiver is just not responding at all. Have you enabled the server in it's settings? it can either be set to network or serial/uart. It must be set to network. I don't remember where in the menu it is.

**Comment by Setaas** [comment]
I had a look into the manual and the only server I see is DHCP, but probably that's not the case.
https://www.arcam.co.uk/ugc/tor/avr360/User%20Manual/AVR360_MANUAL_SH238_E-F-ES-D-NL_230V_1.pdf

If this server couldn't be runnig, could I access it via web browser and/or add receiver into HA using port 80 instead of 50000?

**Comment by elupus** [comment]
on port 80 and normally 8080 there is a webserver on port 50000 there should be an rs232 interface. However, this looks to have been a wild goose chase. the receiver you have does not support rs232 over network.
https://www.arcam.co.uk/ugc/tor/avr360/RS232/AVR400_RS232_SH235_E_1.2.pdf

If you look at one that does support it: https://www.arcam.co.uk/ugc/tor/avr450/RS232/RS232_AVR750450380_SH256E_3.pdf

It calls it RS232/NET.

Now given that.. If you do hook up some type of serial to network dongle to the serial port on the back of your device, it should theoretically work with this integration.

**Comment by bjtallguy** [comment]
Setaas: I have a similar problem with my AV250, which I believe uses the same ARM chipset and server software. 
If you use any other network service (Home Media Server, Spotify Connect, Streaming Digital Radio, AirPlay), then network remote control stops working. 
I find this with Elupus' arcam_fmj and the official Arcam iOS App. The remote control API simply does not respond at all. I have also shown this with network scanning tools. 
The only solution I have found, is to power off and back on again.

**Comment by bjtallguy** [comment]
Elupus: Good idea about using RS232. I use Volumio on a RaspPi and your library to remote control my amp. I am going to build an RS232 interface to see if I can reset the network API server when it stop responding. 
I even considered an infra-red module, but RS232 makes more sense.

**Comment by Setaas** [comment]
Thank you Guys for your help and support. I will think about the possibilities shared here. Anyway, seems like the easiest way will be receivier upgrade ;)
